
# MybatisPlus beg
# DataSource Config
# mysql 5 驱动不同 com.mysql.jdbc.Driver
# mysql 8 驱动不同com.mysql.cj.jdbc.Driver、需要增加时区的配置 serverTimezone=GMT%2B8
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/mybatisplus? useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: localhost
# MybatisPlus end
server:
  port: 8082
