server:
  port: 8085

taco:
  orders:
    pageSize: 30


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity? useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: localhost
    driver-class-name: com.mysql.cj.jdbc.Driver